### ISSUE TITLE
Incorrect Syntax in MDOP Query

### ISSUE THREAD

**Issue by CalvinistNerd** [stephaneserero/Sql-recommendations-for-MECM#2]
In your first query, for checking and setting the Recommended MDOP, line 19 according to your paper, it says

`SELECT parent node id AS [NumaNodeId]`

when it should read

`SELECT parent_node_id AS [NumaNodeId]`

**Comment by stephaneserero** [comment]
Thanks for the head up! We will fix that

Regards
Stephane
